<?php

/**
 * @package     Joomla.Administrator
 * @subpackage  com_workflow
 *
 * @copyright   (C) 2025 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @since       DEPLOY_VERSION
 */

namespace Joomla\Component\Workflow\Administrator\Model;

use Joomla\CMS\MVC\Model\AdminModel;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects

/**
 * Model class for Grpaphical View of the workflow
 *
 * @since  DEPLOY_VERSION
 */
class GraphModel extends AdminModel
{
    protected $table = '#__workflow';

    /**
     * Abstract method for getting the form from the model.
     *
     * @param   array    $data      Data for the form.
     * @param   boolean  $loadData  True if the form is to load its own data (default case), false if not.
     *
     * @return  Form|boolean A Form object on success, false on failure
     *
     * @since   DEPLOY_VERSION
     */
    public function getForm($data = [], $loadData = true)
    {
        // Load the form.
        return false;
    }

    public function getTable($name = '', $prefix = '', $options = [])
    {
        return parent::getTable($name, $prefix, $options); // TODO: Change the autogenerated stub
    }

    public function getStages($workflowId)
    {
        return true;
    }

    public function getTransitions($workflowId)
    {
        return true;
    }
}
